source 'git@github.com:CocoaPods/Specs.git'
platform :ios, '13.0'
use_frameworks!

target 'DoKitSwiftDemo' do
  pod 'FBRetainCycleDetector', :git => "https://github.com/TrailSquad/FBRetainCycleDetector", :configurations => ['Debug']
  pod 'DoraemonKit', :subspecs => ['Core'],  :path => '../../../', :configurations => ['Debug']
  pod 'DoraemonKit', :subspecs => ['WithGPS'],  :path => '../../../', :configurations => ['Debug']
  pod 'DoraemonKit', :subspecs => ['WithMLeaksFinder'],  :path => '../../../', :configurations => ['Debug']
  pod 'AFNetworking'
end
