#source 'git@github.com:CocoaPods/Specs.git'
platform :ios, '13.0'
use_frameworks!

target 'DoKitSwiftDemo' do
  pod 'FBRetainCycleDetector', :git => "https://github.com/TrailSquad/FBRetainCycleDetector", :configurations => ['Debug']
  pod 'DoraemonKit', :subspecs => ['Core'],  :path => '../../../', :configurations => ['Debug']
  pod 'DoraemonKit', :subspecs => ['WithGPS'],  :path => '../../../', :configurations => ['Debug']
  pod 'DoraemonKit', :subspecs => ['WithMLeaksFinder'],  :path => '../../../', :configurations => ['Debug']
  pod 'AFNetworking'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
         end
    end
  end
end
